version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/freeocronline.in/
permissions:
   - object: /var/www/html/freeocronline.in/
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file